In [ ]:
# ============================================================
# AI REALIZATION GAP — EU27
# STEP 05 — MASTER DATASET & AI REALIZATION GAP
# ============================================================

from google.colab import drive
from pathlib import Path

import pandas as pd
import numpy as np
import json
from datetime import datetime

drive.mount("/content/drive")

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Realization_Gap_EU27"
)

ADMIN_DIR = PROJECT_ROOT / "00_admin"
INTERMEDIATE_DIR = PROJECT_ROOT / "02_intermediate_data"
PROCESSED_DIR = PROJECT_ROOT / "03_processed_data"
TABLE_DIR = PROJECT_ROOT / "05_tables"
LOG_DIR = PROJECT_ROOT / "08_logs"

AI_YEARS = [2021, 2023, 2024, 2025]

print("Project root:", PROJECT_ROOT)
print("Analysis years:", AI_YEARS)

Mounted at /content/drive
Project root: /content/drive/MyDrive/AI_Realization_Gap_EU27
Analysis years: [2021, 2023, 2024, 2025]

In [ ]:
# ============================================================
# LOAD STEP 02 — AI ADOPTION
# ============================================================

step02_path = (
    PROCESSED_DIR /
    "Step_02_AI_adoption_EU27_2021_2023_2024_2025.csv"
)

adoption = pd.read_csv(step02_path)

print("Step 02:", adoption.shape)
display(adoption.head())

Step 02: (108, 6)

  geo  country iso3  year  ai_adoption_pct  ai_adoption
0  AT  Austria  AUT  2021             8.83       0.0883
1  AT  Austria  AUT  2023            10.79       0.1079
2  AT  Austria  AUT  2024            20.27       0.2027
3  AT  Austria  AUT  2025            29.95       0.2995
4  BE  Belgium  BEL  2021            10.32       0.1032

In [ ]:
# ============================================================
# LOAD STEP 03 — AI POTENTIAL
# ============================================================

step03_path = (
    PROCESSED_DIR /
    "Step_03_AI_potential_EU27_2021_2023_2024_2025.csv"
)

potential = pd.read_csv(step03_path)

print("Step 03:", potential.shape)
display(potential.head())

Step 03: (108, 14)

,geo,country,iso3,year,ict_specialists_pct,hrst_pct,hightech_emp_pct,z_ict_specialists_pct,z_hrst_pct,z_hightech_emp_pct,ai_potential_pca_z,ai_potential,ai_potential_equal_z,ai_potential_equal
0,AT,Austria,AUT,2021,4.5,52.3,4.5,-0.434344,0.063450,-0.726923,-0.353444,0.412078,-0.365939,0.401139
1,AT,Austria,AUT,2023,5.3,54.5,5.1,0.118341,0.296820,-0.271366,0.059850,0.520042,0.047932,0.507658
2,AT,Austria,AUT,2024,5.3,55.2,5.2,0.118341,0.371074,-0.195440,0.108651,0.532790,0.097992,0.520542
3,AT,Austria,AUT,2025,5.4,55.3,5.4,0.187427,0.381681,-0.043587,0.183101,0.552239,0.175174,0.540407
4,BE,Belgium,BEL,2021,5.6,58.7,5.7,0.325598,0.742344,0.184191,0.425134,0.615464,0.417378,0.602743

In [ ]:
# ============================================================
# LOAD STEP 04 — COMPLEMENTARY ENABLERS
# ============================================================

step04_path = (
    PROCESSED_DIR /
    "Step_04_Complementary_Enablers_EU27.csv"
)

enablers = pd.read_csv(step04_path)

print("Step 04:", enablers.shape)
display(enablers.head())

Step 04: (108, 7)

  geo  country iso3  year  vhcn_pct  gdp_pc_pps  ln_gdp_pc_pps
0  AT  Austria  AUT  2021      45.4     40185.6      10.601264
1  AT  Austria  AUT  2023      67.6     46391.9      10.744880
2  AT  Austria  AUT  2024      72.2     47527.9      10.769072
3  AT  Austria  AUT  2025      76.3     49029.2      10.800171
4  BE  Belgium  BEL  2021      68.9     38699.2      10.563574

In [ ]:
# ============================================================
# CHECK REQUIRED VARIABLES
# ============================================================

required_adoption = [
    "geo",
    "country",
    "iso3",
    "year",
    "ai_adoption_pct",
    "ai_adoption"
]

required_potential = [
    "geo",
    "country",
    "iso3",
    "year",
    "ict_specialists_pct",
    "hrst_pct",
    "hightech_emp_pct",
    "ai_potential_pca_z",
    "ai_potential",
    "ai_potential_equal_z",
    "ai_potential_equal"
]

required_enablers = [
    "geo",
    "country",
    "iso3",
    "year",
    "vhcn_pct",
    "gdp_pc_pps",
    "ln_gdp_pc_pps"
]

for name, df, required in [
    ("Step 02", adoption, required_adoption),
    ("Step 03", potential, required_potential),
    ("Step 04", enablers, required_enablers)
]:

    missing_cols = [
        col for col in required
        if col not in df.columns
    ]

    print(name, "missing columns:", missing_cols)

Step 02 missing columns: []
Step 03 missing columns: []
Step 04 missing columns: []

In [ ]:
# ============================================================
# MERGE ADOPTION + POTENTIAL
# ============================================================

master = adoption[
    required_adoption
].merge(

    potential[
        required_potential
    ],

    on=[
        "geo",
        "country",
        "iso3",
        "year"
    ],

    how="inner",
    validate="one_to_one"
)

print("After Step 02 + Step 03:", master.shape)

After Step 02 + Step 03: (108, 13)

In [ ]:
# ============================================================
# ADD COMPLEMENTARY ENABLERS
# ============================================================

master = master.merge(

    enablers[
        required_enablers
    ],

    on=[
        "geo",
        "country",
        "iso3",
        "year"
    ],

    how="inner",
    validate="one_to_one"
)

master = (
    master
    .sort_values(
        ["iso3", "year"]
    )
    .reset_index(drop=True)
)

print("Master panel shape:", master.shape)

display(master.head(15))

Master panel shape: (108, 16)

,geo,country,iso3,year,ai_adoption_pct,ai_adoption,ict_specialists_pct,hrst_pct,hightech_emp_pct,ai_potential_pca_z,ai_potential,ai_potential_equal_z,ai_potential_equal,vhcn_pct,gdp_pc_pps,ln_gdp_pc_pps
0,AT,Austria,AUT,2021,8.83,0.0883,4.5,52.3,4.5,-0.353444,0.412078,-0.365939,0.401139,45.4,40185.6,10.601264
1,AT,Austria,AUT,2023,10.79,0.1079,5.3,54.5,5.1,0.059850,0.520042,0.047932,0.507658,67.6,46391.9,10.744880
2,AT,Austria,AUT,2024,20.27,0.2027,5.3,55.2,5.2,0.108651,0.532790,0.097992,0.520542,72.2,47527.9,10.769072
3,AT,Austria,AUT,2025,29.95,0.2995,5.4,55.3,5.4,0.183101,0.552239,0.175174,0.540407,76.3,49029.2,10.800171
4,BE,Belgium,BEL,2021,10.32,0.1032,5.6,58.7,5.7,0.425134,0.615464,0.417378,0.602743,68.9,38699.2,10.563574
5,BE,Belgium,BEL,2023,13.81,0.1381,5.4,58.5,5.5,0.322885,0.588754,0.313631,0.576042,91.2,45367.3,10.722547
6,BE,Belgium,BEL,2024,24.71,0.2471,5.7,59.0,5.6,0.436886,0.618534,0.425705,0.604886,93.8,46587.9,10.749096
7,BE,Belgium,BEL,2025,34.54,0.3454,5.9,61.7,5.9,0.653443,0.675105,0.643158,0.660853,96.2,47676.3,10.772190
8,BG,Bulgaria,BGR,2021,3.29,0.0329,3.5,38.5,4.5,-1.097265,0.217772,-1.084180,0.216285,81.4,19748.1,9.890813
9,BG,Bulgaria,BGR,2023,3.62,0.0362,4.3,39.0,5.1,-0.745839,0.309574,-0.730419,0.307333,88.6,24254.4,10.096353
10,BG,Bulgaria,BGR,2024,6.47,0.0647,4.6,43.0,5.1,-0.527788,0.366535,-0.519897,0.361515,90.4,26324.3,10.178248
11,BG,Bulgaria,BGR,2025,8.55,0.0855,4.8,46.4,5.3,-0.309081,0.423667,-0.303002,0.417338,93.5,28332.0,10.251747
12,CY,Cyprus,CYP,2021,2.59,0.0259,3.9,54.8,3.9,-0.547372,0.361419,-0.567565,0.349247,41.4,30382.9,10.321635
13,CY,Cyprus,CYP,2023,4.67,0.0467,5.6,58.2,6.3,0.546892,0.647271,0.551551,0.637275,77.1,37400.0,10.529426
14,CY,Cyprus,CYP,2024,7.90,0.0790,5.0,58.9,5.5,0.240805,0.567312,0.235661,0.555974,89.0,39456.4,10.582952

In [ ]:
# ============================================================
# MASTER DATASET BASIC QC
# ============================================================

print("Rows:", len(master))
print("Countries:", master["iso3"].nunique())
print("Years:", sorted(master["year"].unique()))

print(
    "Duplicates:",
    master.duplicated(
        ["iso3", "year"]
    ).sum()
)

print("\nMissing values:")

display(
    master
    .isna()
    .sum()
    .to_frame("missing_n")
)

Rows: 108
Countries: 27
Years: [np.int64(2021), np.int64(2023), np.int64(2024), np.int64(2025)]
Duplicates: 0

Missing values:

                      missing_n
geo                           0
country                       0
iso3                          0
year                          0
ai_adoption_pct               0
ai_adoption                   0
ict_specialists_pct           0
hrst_pct                      0
hightech_emp_pct              0
ai_potential_pca_z            0
ai_potential                  0
ai_potential_equal_z          0
ai_potential_equal            0
vhcn_pct                      0
gdp_pc_pps                    0
ln_gdp_pc_pps                 0

In [ ]:
# ============================================================
# MIN-MAX NORMALIZE AI ADOPTION
# ACROSS ALL 108 COUNTRY-YEAR OBSERVATIONS
# ============================================================

adopt_min = master[
    "ai_adoption_pct"
].min()

adopt_max = master[
    "ai_adoption_pct"
].max()

master["ai_adoption_norm"] = (
    master["ai_adoption_pct"]
    - adopt_min
) / (
    adopt_max
    - adopt_min
)

print("Adoption original range:")
print(
    master["ai_adoption_pct"]
    .min(),
    master["ai_adoption_pct"]
    .max()
)

print("\nNormalized range:")
print(
    master["ai_adoption_norm"]
    .min(),
    master["ai_adoption_norm"]
    .max()
)

Adoption original range:
1.38 42.03

Normalized range:
0.0 1.0

In [ ]:
# ============================================================
# MAIN AI REALIZATION GAP
# ============================================================

master["ai_realization_gap"] = (
    master["ai_potential"]
    -
    master["ai_adoption_norm"]
)

display(
    master[
        [
            "country",
            "year",
            "ai_potential",
            "ai_adoption_pct",
            "ai_adoption_norm",
            "ai_realization_gap"
        ]
    ].head(20)
)

,country,year,ai_potential,ai_adoption_pct,ai_adoption_norm,ai_realization_gap
0,Austria,2021,0.412078,8.83,0.183272,0.228807
1,Austria,2023,0.520042,10.79,0.231488,0.288554
2,Austria,2024,0.532790,20.27,0.464699,0.068092
3,Austria,2025,0.552239,29.95,0.702829,-0.150590
4,Belgium,2021,0.615464,10.32,0.219926,0.395538
5,Belgium,2023,0.588754,13.81,0.305781,0.282973
6,Belgium,2024,0.618534,24.71,0.573924,0.044610
7,Belgium,2025,0.675105,34.54,0.815744,-0.140639
8,Bulgaria,2021,0.217772,3.29,0.046986,0.170786
9,Bulgaria,2023,0.309574,3.62,0.055105,0.254470
10,Bulgaria,2024,0.366535,6.47,0.125215,0.241320
11,Bulgaria,2025,0.423667,8.55,0.176384,0.247284
12,Cyprus,2021,0.361419,2.59,0.029766,0.331653
13,Cyprus,2023,0.647271,4.67,0.080935,0.566336
14,Cyprus,2024,0.567312,7.90,0.160394,0.406919
15,Cyprus,2025,0.549376,9.27,0.194096,0.355280
16,Czechia,2021,0.393588,4.46,0.075769,0.317819
17,Czechia,2023,0.362079,5.90,0.111193,0.250886
18,Czechia,2024,0.387060,11.26,0.243050,0.144010
19,Czechia,2025,0.431272,17.60,0.399016,0.032256

In [ ]:
# ============================================================
# DESCRIPTIVE GAP CLASSIFICATION
# ============================================================

master["gap_direction"] = np.select(

    [
        master["ai_realization_gap"] > 0,
        master["ai_realization_gap"] < 0
    ],

    [
        "Potential exceeds adoption",
        "Adoption exceeds potential"
    ],

    default="Balanced"
)

display(
    master[
        [
            "country",
            "year",
            "ai_realization_gap",
            "gap_direction"
        ]
    ].head(20)
)

     country  year  ai_realization_gap               gap_direction
0    Austria  2021            0.228807  Potential exceeds adoption
1    Austria  2023            0.288554  Potential exceeds adoption
2    Austria  2024            0.068092  Potential exceeds adoption
3    Austria  2025           -0.150590  Adoption exceeds potential
4    Belgium  2021            0.395538  Potential exceeds adoption
5    Belgium  2023            0.282973  Potential exceeds adoption
6    Belgium  2024            0.044610  Potential exceeds adoption
7    Belgium  2025           -0.140639  Adoption exceeds potential
8   Bulgaria  2021            0.170786  Potential exceeds adoption
9   Bulgaria  2023            0.254470  Potential exceeds adoption
10  Bulgaria  2024            0.241320  Potential exceeds adoption
11  Bulgaria  2025            0.247284  Potential exceeds adoption
12    Cyprus  2021            0.331653  Potential exceeds adoption
13    Cyprus  2023            0.566336  Potential exceeds adoption
14    Cyprus  2024            0.406919  Potential exceeds adoption
15    Cyprus  2025            0.355280  Potential exceeds adoption
16   Czechia  2021            0.317819  Potential exceeds adoption
17   Czechia  2023            0.250886  Potential exceeds adoption
18   Czechia  2024            0.144010  Potential exceeds adoption
19   Czechia  2025            0.032256  Potential exceeds adoption

In [ ]:
# ============================================================
# STANDARDIZED ADOPTION
# ============================================================

adopt_mean = master[
    "ai_adoption_pct"
].mean()

adopt_std = master[
    "ai_adoption_pct"
].std(ddof=0)

master["z_ai_adoption"] = (
    master["ai_adoption_pct"]
    - adopt_mean
) / adopt_std

In [ ]:
# ============================================================
# Z-SCORE REALIZATION GAP — ROBUSTNESS
# ============================================================

master["ai_realization_gap_z"] = (
    master["ai_potential_pca_z"]
    -
    master["z_ai_adoption"]
)

display(
    master[
        [
            "country",
            "year",
            "ai_realization_gap",
            "ai_realization_gap_z"
        ]
    ].head(20)
)

     country  year  ai_realization_gap  ai_realization_gap_z
0    Austria  2021            0.228807              0.094730
1    Austria  2023            0.288554              0.283173
2    Austria  2024            0.068092             -0.755577
3    Austria  2025           -0.150590             -1.791622
4    Belgium  2021            0.395538              0.702375
5    Belgium  2023            0.282973              0.199752
6    Belgium  2024            0.044610             -0.936701
7    Belgium  2025           -0.140639             -1.847846
8   Bulgaria  2021            0.170786             -0.013538
9   Bulgaria  2023            0.254470              0.300030
10  Bulgaria  2024            0.241320              0.191127
11  Bulgaria  2025            0.247284              0.171216
12    Cyprus  2021            0.331653              0.616659
13    Cyprus  2023            0.566336              1.472304
14    Cyprus  2024            0.406919              0.795670
15    Cyprus  2025            0.355280              0.569842
16   Czechia  2021            0.317819              0.525277
17   Czechia  2023            0.250886              0.239460
18   Czechia  2024            0.144010             -0.279812
19   Czechia  2025            0.032256             -0.837894

In [ ]:
# ============================================================
# EQUAL-WEIGHT GAP — ROBUSTNESS
# ============================================================

master["ai_realization_gap_equal"] = (
    master["ai_potential_equal"]
    -
    master["ai_adoption_norm"]
)

display(
    master[
        [
            "country",
            "year",
            "ai_realization_gap",
            "ai_realization_gap_equal"
        ]
    ].head()
)

   country  year  ai_realization_gap  ai_realization_gap_equal
0  Austria  2021            0.228807                  0.217868
1  Austria  2023            0.288554                  0.276170
2  Austria  2024            0.068092                  0.055844
3  Austria  2025           -0.150590                 -0.162422
4  Belgium  2021            0.395538                  0.382817

In [ ]:
# ============================================================
# ROBUSTNESS CORRELATION
# ============================================================

gap_corr = master[
    [
        "ai_realization_gap",
        "ai_realization_gap_z",
        "ai_realization_gap_equal"
    ]
].corr()

display(gap_corr)

,ai_realization_gap,ai_realization_gap_z,ai_realization_gap_equal
ai_realization_gap,1.000000,0.982109,0.999426
ai_realization_gap_z,0.982109,1.000000,0.985445
ai_realization_gap_equal,0.999426,0.985445,1.000000

In [ ]:
# ============================================================
# CORE DESCRIPTIVE STATISTICS
# ============================================================

core_vars = [
    "ai_adoption_pct",
    "ai_potential",
    "ai_realization_gap",
    "vhcn_pct",
    "gdp_pc_pps",
    "ln_gdp_pc_pps"
]

descriptive = (
    master[core_vars]
    .describe()
    .T
)

display(descriptive)

,count,mean,std,min,25%,50%,75%,max
ai_adoption_pct,108.0,12.736667,8.757474,1.380000,6.395000,10.345000,17.375000,42.030000
ai_potential,108.0,0.504408,0.231680,0.000000,0.372646,0.474507,0.668239,1.000000
ai_realization_gap,108.0,0.225031,0.206330,-0.298495,0.079815,0.224130,0.340463,0.814819
vhcn_pct,108.0,79.835185,15.855871,19.800000,71.775000,81.550000,93.575000,100.000000
gdp_pc_pps,108.0,39817.061111,16356.244024,19748.100000,29837.525000,36198.400000,43913.825000,99621.300000
ln_gdp_pc_pps,108.0,10.530364,0.331614,9.890813,10.303522,10.496770,10.689975,11.509131

In [ ]:
# ============================================================
# YEARLY GAP SUMMARY
# ============================================================

gap_by_year = (
    master
    .groupby("year")
    ["ai_realization_gap"]
    .agg(
        N="count",
        mean="mean",
        median="median",
        std="std",
        min="min",
        max="max"
    )
    .reset_index()
)

display(gap_by_year)

   year   N      mean    median       std       min       max
0  2021  27  0.294069  0.281815  0.189059  0.001152  0.814819
1  2023  27  0.328293  0.288554  0.193932 -0.003198  0.806433
2  2024  27  0.211941  0.210622  0.163370 -0.087249  0.667405
3  2025  27  0.065821  0.032256  0.180651 -0.298495  0.544661

In [ ]:
# ============================================================
# COUNTRY AVERAGE GAP
# ============================================================

gap_by_country = (
    master
    .groupby(
        ["iso3", "country"]
    )
    ["ai_realization_gap"]
    .agg(
        mean_gap="mean",
        median_gap="median",
        min_gap="min",
        max_gap="max"
    )
    .reset_index()
    .sort_values(
        "mean_gap",
        ascending=False
    )
)

display(gap_by_country)

   iso3      country  mean_gap  median_gap   min_gap   max_gap
14  IRL      Ireland  0.708329    0.736919  0.544661  0.814819
8   EST      Estonia  0.462510    0.508938  0.200409  0.631757
26  SWE       Sweden  0.458025    0.486892  0.134403  0.723915
3   CYP       Cyprus  0.415047    0.381100  0.331653  0.566336
17  LUX   Luxembourg  0.363234    0.388081  0.129817  0.546957
13  HUN      Hungary  0.313545    0.333409  0.237512  0.349851
16  LTU    Lithuania  0.309824    0.342919  0.141245  0.412213
21  POL       Poland  0.281225    0.287762  0.230802  0.318576
18  LVA       Latvia  0.273183    0.286516  0.181095  0.338606
10  FRA       France  0.267993    0.298725  0.110699  0.363825
20  NLD  Netherlands  0.261271    0.315355 -0.012612  0.426985
9   FIN      Finland  0.248963    0.321571 -0.106688  0.459399
2   BGR     Bulgaria  0.228465    0.244302  0.170786  0.254470
4   CZE      Czechia  0.186243    0.197448  0.032256  0.317819
22  PRT     Portugal  0.171777    0.163612  0.149261  0.210622
24  SVK     Slovakia  0.161532    0.188379  0.007674  0.261697
19  MLT        Malta  0.155550    0.187478  0.002274  0.244971
1   BEL      Belgium  0.145620    0.163792 -0.140639  0.395538
5   DEU      Germany  0.141129    0.170937 -0.041789  0.264431
25  SVN     Slovenia  0.125348    0.077831 -0.004089  0.349819
7   ESP        Spain  0.115661    0.167367 -0.049460  0.177370
0   AUT      Austria  0.108715    0.148449 -0.150590  0.288554
12  HRV      Croatia  0.099208    0.118303  0.001152  0.159073
6   DNK      Denmark  0.049972    0.069351 -0.298495  0.359679
15  ITA        Italy  0.039535    0.077459 -0.153750  0.156972
11  GRC       Greece -0.000903    0.002890 -0.087249  0.077857
23  ROU      Romania -0.015170   -0.006654 -0.064313  0.016940

In [ ]:
# ============================================================
# CHANGE IN REALIZATION GAP: 2021 → 2025
# ============================================================

gap_wide = (
    master[
        [
            "iso3",
            "country",
            "year",
            "ai_realization_gap"
        ]
    ]
    .pivot(
        index=["iso3", "country"],
        columns="year",
        values="ai_realization_gap"
    )
    .reset_index()
)

gap_wide["gap_change_2021_2025"] = (
    gap_wide[2025]
    -
    gap_wide[2021]
)

display(
    gap_wide.sort_values(
        "gap_change_2021_2025"
    )
)

year,iso3,country,2021,2023,2024,2025,gap_change_2021_2025
1,BEL,Belgium,0.395538,0.282973,0.044610,-0.140639,-0.536177
9,FIN,Finland,0.401627,0.459399,0.241514,-0.106688,-0.508315
26,SWE,Sweden,0.622486,0.723915,0.351297,0.134403,-0.488083
8,EST,Estonia,0.631757,0.599026,0.418850,0.200409,-0.431348
20,NLD,Netherlands,0.415368,0.426985,0.215341,-0.012612,-0.427980
0,AUT,Austria,0.228807,0.288554,0.068092,-0.150590,-0.379397
6,DNK,Denmark,0.080165,0.359679,0.058537,-0.298495,-0.378660
25,SVN,Slovenia,0.349819,0.151143,-0.004089,0.004520,-0.345300
17,LUX,Luxembourg,0.445743,0.546957,0.330419,0.129817,-0.315926
5,DEU,Germany,0.264431,0.263110,0.078764,-0.041789,-0.306220
4,CZE,Czechia,0.317819,0.250886,0.144010,0.032256,-0.285563
14,IRL,Ireland,0.814819,0.806433,0.667405,0.544661,-0.270158
24,SVK,Slovakia,0.261697,0.191207,0.185551,0.007674,-0.254023
19,MLT,Malta,0.244971,0.219453,0.155504,0.002274,-0.242697
15,ITA,Italy,0.074143,0.156972,0.080776,-0.153750,-0.227893
7,ESP,Spain,0.166846,0.177370,0.167889,-0.049460,-0.216305
10,FRA,France,0.313705,0.363825,0.283745,0.110699,-0.203006
16,LTU,Lithuania,0.298255,0.412213,0.387583,0.141245,-0.157009
11,GRC,Greece,0.077857,0.058243,-0.087249,-0.052464,-0.130321
13,HUN,Hungary,0.349851,0.346032,0.320786,0.237512,-0.112339
18,LVA,Latvia,0.281815,0.338606,0.291217,0.181095,-0.100721
23,ROU,Romania,0.016940,-0.003198,-0.010111,-0.064313,-0.081253
3,CYP,Cyprus,0.331653,0.566336,0.406919,0.355280,0.023627
22,PRT,Portugal,0.151020,0.149261,0.210622,0.176203,0.025183
21,POL,Poland,0.230802,0.318576,0.314023,0.261501,0.030699
2,BGR,Bulgaria,0.170786,0.254470,0.241320,0.247284,0.076498
12,HRV,Croatia,0.001152,0.155475,0.159073,0.081131,0.079980

In [ ]:
# ============================================================
# ADD CLOUD AS AUXILIARY VARIABLE
# ============================================================

cloud_path = (
    INTERMEDIATE_DIR /
    "Step_04_Cloud_auxiliary_EU27.csv"
)

cloud_aux = pd.read_csv(
    cloud_path
)

master = master.merge(

    cloud_aux[
        [
            "geo",
            "year",
            "cloud_pct"
        ]
    ],

    on=[
        "geo",
        "year"
    ],

    how="left",
    validate="one_to_one"
)

print(
    "Cloud observed:",
    master["cloud_pct"].notna().sum()
)

print(
    "Cloud missing:",
    master["cloud_pct"].isna().sum()
)

Cloud observed: 85
Cloud missing: 23

In [ ]:
# ============================================================
# FINAL COLUMN ORDER
# ============================================================

final_cols = [

    # identifiers
    "geo",
    "country",
    "iso3",
    "year",

    # realized AI
    "ai_adoption_pct",
    "ai_adoption",
    "ai_adoption_norm",
    "z_ai_adoption",

    # AI potential components
    "ict_specialists_pct",
    "hrst_pct",
    "hightech_emp_pct",

    # AI potential
    "ai_potential_pca_z",
    "ai_potential",
    "ai_potential_equal_z",
    "ai_potential_equal",

    # main outcome
    "ai_realization_gap",

    # robustness outcomes
    "ai_realization_gap_z",
    "ai_realization_gap_equal",

    # complementary enablers
    "vhcn_pct",
    "gdp_pc_pps",
    "ln_gdp_pc_pps",

    # auxiliary
    "cloud_pct"
]

master_final = (
    master[final_cols]
    .sort_values(
        ["iso3", "year"]
    )
    .reset_index(drop=True)
)

print(master_final.shape)

display(master_final.head(20))

(108, 22)

,geo,country,iso3,year,ai_adoption_pct,ai_adoption,ai_adoption_norm,z_ai_adoption,ict_specialists_pct,hrst_pct,...,ai_potential,ai_potential_equal_z,ai_potential_equal,ai_realization_gap,ai_realization_gap_z,ai_realization_gap_equal,vhcn_pct,gdp_pc_pps,ln_gdp_pc_pps,cloud_pct
0,AT,Austria,AUT,2021,8.83,0.0883,0.183272,-0.448175,4.5,52.3,...,0.412078,-0.365939,0.401139,0.228807,0.094730,0.217868,45.4,40185.6,10.601264,39.73
1,AT,Austria,AUT,2023,10.79,0.1079,0.231488,-0.223323,5.3,54.5,...,0.520042,0.047932,0.507658,0.288554,0.283173,0.276170,67.6,46391.9,10.744880,46.06
2,AT,Austria,AUT,2024,20.27,0.2027,0.464699,0.864228,5.3,55.2,...,0.532790,0.097992,0.520542,0.068092,-0.755577,0.055844,72.2,47527.9,10.769072,NaN
3,AT,Austria,AUT,2025,29.95,0.2995,0.702829,1.974723,5.4,55.3,...,0.552239,0.175174,0.540407,-0.150590,-1.791622,-0.162422,76.3,49029.2,10.800171,51.68
4,BE,Belgium,BEL,2021,10.32,0.1032,0.219926,-0.277241,5.6,58.7,...,0.615464,0.417378,0.602743,0.395538,0.702375,0.382817,68.9,38699.2,10.563574,52.50
5,BE,Belgium,BEL,2023,13.81,0.1381,0.305781,0.123133,5.4,58.5,...,0.588754,0.313631,0.576042,0.282973,0.199752,0.270261,91.2,45367.3,10.722547,51.23
6,BE,Belgium,BEL,2024,24.71,0.2471,0.573924,1.373587,5.7,59.0,...,0.618534,0.425705,0.604886,0.044610,-0.936701,0.030963,93.8,46587.9,10.749096,NaN
7,BE,Belgium,BEL,2025,34.54,0.3454,0.815744,2.501290,5.9,61.7,...,0.675105,0.643158,0.660853,-0.140639,-1.847846,-0.154892,96.2,47676.3,10.772190,61.04
8,BG,Bulgaria,BGR,2021,3.29,0.0329,0.046986,-1.083727,3.5,38.5,...,0.217772,-1.084180,0.216285,0.170786,-0.013538,0.169298,81.4,19748.1,9.890813,12.69
9,BG,Bulgaria,BGR,2023,3.62,0.0362,0.055105,-1.045869,4.3,39.0,...,0.309574,-0.730419,0.307333,0.254470,0.300030,0.252228,88.6,24254.4,10.096353,17.43
10,BG,Bulgaria,BGR,2024,6.47,0.0647,0.125215,-0.718915,4.6,43.0,...,0.366535,-0.519897,0.361515,0.241320,0.191127,0.236300,90.4,26324.3,10.178248,NaN
11,BG,Bulgaria,BGR,2025,8.55,0.0855,0.176384,-0.480297,4.8,46.4,...,0.423667,-0.303002,0.417338,0.247284,0.171216,0.240954,93.5,28332.0,10.251747,17.49
12,CY,Cyprus,CYP,2021,2.59,0.0259,0.029766,-1.164031,3.9,54.8,...,0.361419,-0.567565,0.349247,0.331653,0.616659,0.319480,41.4,30382.9,10.321635,50.29
13,CY,Cyprus,CYP,2023,4.67,0.0467,0.080935,-0.925412,5.6,58.2,...,0.647271,0.551551,0.637275,0.566336,1.472304,0.556341,77.1,37400.0,10.529426,52.93
14,CY,Cyprus,CYP,2024,7.90,0.0790,0.160394,-0.554865,5.0,58.9,...,0.567312,0.235661,0.555974,0.406919,0.795670,0.395581,89.0,39456.4,10.582952,NaN
15,CY,Cyprus,CYP,2025,9.27,0.0927,0.194096,-0.397698,4.9,59.6,...,0.549376,0.161457,0.536876,0.355280,0.569842,0.342781,95.5,40957.0,10.620278,51.38
16,CZ,Czechia,CZE,2021,4.46,0.0446,0.075769,-0.949504,4.6,42.0,...,0.393588,-0.403404,0.391497,0.317819,0.525277,0.315728,52.5,30502.4,10.325561,43.75
17,CZ,Czechia,CZE,2023,5.90,0.0590,0.111193,-0.784306,4.3,42.6,...,0.362079,-0.527200,0.359635,0.250886,0.239460,0.248442,50.5,34973.9,10.462357,47.15
18,CZ,Czechia,CZE,2024,11.26,0.1126,0.243050,-0.169404,4.5,43.9,...,0.387060,-0.435177,0.383320,0.144010,-0.279812,0.140269,53.9,36255.5,10.498346,NaN
19,CZ,Czechia,CZE,2025,17.60,0.1760,0.399016,0.557924,4.7,45.3,...,0.431272,-0.263691,0.427455,0.032256,-0.837894,0.028439,54.7,38557.0,10.559893,54.90

In [ ]:
# ============================================================
# STEP 05 FINAL QC
# ============================================================

core_complete_vars = [
    "ai_adoption_pct",
    "ai_potential",
    "ai_realization_gap",
    "vhcn_pct",
    "gdp_pc_pps",
    "ln_gdp_pc_pps"
]

qc_checks = {

    "Panel N = 108":
        len(master_final) == 108,

    "Countries = 27":
        master_final[
            "iso3"
        ].nunique() == 27,

    "Years = 4":
        master_final[
            "year"
        ].nunique() == 4,

    "Correct years":
        set(
            master_final["year"]
        ) == {2021, 2023, 2024, 2025},

    "No duplicate country-year":
        master_final.duplicated(
            ["iso3", "year"]
        ).sum() == 0,

    "Core variables complete":
        master_final[
            core_complete_vars
        ].isna().sum().sum() == 0,

    "AI potential in [0,1]":
        (
            master_final[
                "ai_potential"
            ].between(0, 1)
        ).all(),

    "Normalized adoption in [0,1]":
        (
            master_final[
                "ai_adoption_norm"
            ].between(0, 1)
        ).all(),

    "Gap finite":
        np.isfinite(
            master_final[
                "ai_realization_gap"
            ]
        ).all()
}

qc = pd.DataFrame({
    "check": qc_checks.keys(),
    "passed": qc_checks.values()
})

display(qc)

                          check  passed
0                 Panel N = 108    True
1                Countries = 27    True
2                     Years = 4    True
3                 Correct years    True
4     No duplicate country-year    True
5       Core variables complete    True
6         AI potential in [0,1]    True
7  Normalized adoption in [0,1]    True
8                    Gap finite    True

In [ ]:
# ============================================================
# SAVE MASTER DATASET
# ============================================================

master_path = (
    PROCESSED_DIR /
    "Step_05_Master_AI_Realization_Gap_EU27.csv"
)

master_final.to_csv(
    master_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(master_path)

Saved:
/content/drive/MyDrive/AI_Realization_Gap_EU27/03_processed_data/Step_05_Master_AI_Realization_Gap_EU27.csv

In [ ]:
# ============================================================
# SAVE TABLES
# ============================================================

descriptive.to_csv(
    TABLE_DIR /
    "Step_05_Descriptive_Statistics.csv",
    encoding="utf-8-sig"
)

gap_by_year.to_csv(
    TABLE_DIR /
    "Step_05_Gap_by_Year.csv",
    index=False,
    encoding="utf-8-sig"
)

gap_by_country.to_csv(
    TABLE_DIR /
    "Step_05_Gap_by_Country.csv",
    index=False,
    encoding="utf-8-sig"
)

gap_corr.to_csv(
    TABLE_DIR /
    "Step_05_Gap_Robustness_Correlations.csv",
    encoding="utf-8-sig"
)

In [ ]:
# ============================================================
# SAVE QC
# ============================================================

qc_path = (
    LOG_DIR /
    "Step_05_QC.csv"
)

qc.to_csv(
    qc_path,
    index=False,
    encoding="utf-8-sig"
)

print(qc_path)

/content/drive/MyDrive/AI_Realization_Gap_EU27/08_logs/Step_05_QC.csv

In [ ]:
# ============================================================
# STEP 05 METHODOLOGY LOG
# ============================================================

metadata = {

    "step":
        "Step 05 — Master Dataset and AI Realization Gap",

    "panel":
        "EU27 country-year panel",

    "years":
        AI_YEARS,

    "N_expected":
        108,

    "main_ai_potential":
        "PCA-weighted structural AI potential index",

    "potential_scale":
        "0-1 pooled min-max normalization",

    "adoption_measure":
        "Percentage of enterprises using AI technologies",

    "adoption_normalization":
        "0-1 pooled min-max normalization",

    "main_gap_formula":
        "ai_potential - ai_adoption_norm",

    "robustness_gap_1":
        "ai_potential_pca_z - z_ai_adoption",

    "robustness_gap_2":
        "ai_potential_equal - ai_adoption_norm",

    "main_enablers":
        [
            "VHCN coverage",
            "log GDP per capita PPS"
        ],

    "cloud_status":
        "Auxiliary robustness variable due to incomplete coverage",

    "interpolation":
        False,

    "imputation":
        False,

    "created":
        datetime.now().isoformat()
}

metadata_path = (
    LOG_DIR /
    "Step_05_methodology.json"
)

with open(
    metadata_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

print(metadata_path)

/content/drive/MyDrive/AI_Realization_Gap_EU27/08_logs/Step_05_methodology.json

In [ ]:
# ============================================================
# STEP 05 FINAL REPORT
# ============================================================

print("=" * 72)
print("STEP 05 — MASTER DATASET & AI REALIZATION GAP COMPLETED")
print("=" * 72)

print("Panel N       :", len(master_final))
print("Countries     :", master_final["iso3"].nunique())
print("Years         :", sorted(master_final["year"].unique()))

print(
    "Core missing  :",
    master_final[
        core_complete_vars
    ].isna().sum().sum()
)

print("\nMain realization gap:")

print(
    master_final[
        "ai_realization_gap"
    ].describe()
)

print("\nOutput:")
print(master_path)

print("=" * 72)

========================================================================
STEP 05 — MASTER DATASET & AI REALIZATION GAP COMPLETED
========================================================================
Panel N       : 108
Countries     : 27
Years         : [np.int64(2021), np.int64(2023), np.int64(2024), np.int64(2025)]
Core missing  : 0

Main realization gap:
count    108.000000
mean       0.225031
std        0.206330
min       -0.298495
25%        0.079815
50%        0.224130
75%        0.340463
max        0.814819
Name: ai_realization_gap, dtype: float64

Output:
/content/drive/MyDrive/AI_Realization_Gap_EU27/03_processed_data/Step_05_Master_AI_Realization_Gap_EU27.csv
========================================================================

In [ ]:
# ============================================================
# DOWNLOAD STEP 05 OUTPUTS AS ZIP
# ============================================================

from pathlib import Path
import zipfile
from google.colab import files

step05_files = [
    PROJECT_ROOT / "03_processed_data" / "Step_05_Master_AI_Realization_Gap_EU27.csv",
    PROJECT_ROOT / "05_tables" / "Step_05_Descriptive_Statistics.csv",
    PROJECT_ROOT / "05_tables" / "Step_05_Gap_by_Year.csv",
    PROJECT_ROOT / "05_tables" / "Step_05_Gap_by_Country.csv",
    PROJECT_ROOT / "05_tables" / "Step_05_Gap_Robustness_Correlations.csv",
    PROJECT_ROOT / "08_logs" / "Step_05_QC.csv",
    PROJECT_ROOT / "08_logs" / "Step_05_methodology.json"
]

zip_path = Path("/content/Step_05_outputs.zip")

print("Files to include:\n")

for f in step05_files:
    print(f.name, "->", f.exists())

with zipfile.ZipFile(
    zip_path,
    "w",
    zipfile.ZIP_DEFLATED
) as z:

    for f in step05_files:
        if f.exists():
            z.write(
                f,
                arcname=f.name
            )

print("\nZIP created:")
print(zip_path)

files.download(str(zip_path))

Files to include:

Step_05_Master_AI_Realization_Gap_EU27.csv -> True
Step_05_Descriptive_Statistics.csv -> True
Step_05_Gap_by_Year.csv -> True
Step_05_Gap_by_Country.csv -> True
Step_05_Gap_Robustness_Correlations.csv -> True
Step_05_QC.csv -> True
Step_05_methodology.json -> True

ZIP created:
/content/Step_05_outputs.zip