In [ ]:
# ============================================================
# AI REALIZATION GAP — EU27
# STEP 04 — COMPLEMENTARY ENABLERS
# ============================================================

from google.colab import drive
from pathlib import Path

import requests
import pandas as pd
import numpy as np
import itertools
import json

drive.mount("/content/drive")

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AI_Realization_Gap_EU27"
)

ADMIN_DIR = PROJECT_ROOT / "00_admin"
RAW_DIR = PROJECT_ROOT / "01_raw_data"
INTERMEDIATE_DIR = PROJECT_ROOT / "02_intermediate_data"
PROCESSED_DIR = PROJECT_ROOT / "03_processed_data"
TABLE_DIR = PROJECT_ROOT / "05_tables"
LOG_DIR = PROJECT_ROOT / "08_logs"

for _directory in [ADMIN_DIR, RAW_DIR, INTERMEDIATE_DIR, PROCESSED_DIR, TABLE_DIR, LOG_DIR]:
    _directory.mkdir(parents=True, exist_ok=True)

AI_YEARS = [2021, 2023, 2024, 2025]

country_master = pd.read_csv(
    ADMIN_DIR / "eu27_country_master.csv"
)

EU27 = country_master["geo"].tolist()

print("Countries:", len(EU27))
print("Years:", AI_YEARS)

Mounted at /content/drive
Countries: 27
Years: [2021, 2023, 2024, 2025]

In [ ]:
# ============================================================
# EUROSTAT JSON HELPER
# ============================================================

def ordered_codes(dataset, dim):

    idx = dataset["dimension"][dim]["category"]["index"]

    if isinstance(idx, dict):
        return [
            code
            for code, pos in sorted(
                idx.items(),
                key=lambda x: x[1]
            )
        ]

    return idx


def eurostat_json_to_df(dataset):

    dims = dataset["id"]

    codes = {
        dim: ordered_codes(dataset, dim)
        for dim in dims
    }

    combinations = itertools.product(
        *[codes[d] for d in dims]
    )

    values = dataset.get("value", {})

    records = []

    for i, combination in enumerate(combinations):

        row = dict(zip(dims, combination))

        row["value"] = values.get(
            str(i),
            np.nan
        )

        records.append(row)

    return pd.DataFrame(records)

In [ ]:
# ============================================================
# COMPONENT 1 — FIXED VHCN COVERAGE
# ============================================================

VHCN_DATASET = "isoc_cbt"

vhcn_url = (
    "https://ec.europa.eu/eurostat/api/"
    "dissemination/statistics/1.0/data/"
    f"{VHCN_DATASET}"
    "?lang=en"
    "&sinceTimePeriod=2021"
    "&untilTimePeriod=2025"
)

response = requests.get(
    vhcn_url,
    timeout=180
)

response.raise_for_status()

vhcn_json = response.json()

print("Dimensions:", vhcn_json["id"])
print("Sizes:", vhcn_json["size"])

Dimensions: ['freq', 'unit', 'inet_tec', 'terrtypo', 'geo', 'time']
Sizes: [1, 1, 21, 2, 32, 5]

In [ ]:
vhcn_long = eurostat_json_to_df(
    vhcn_json
)

print(vhcn_long.shape)

display(vhcn_long.head())

(6720, 7)

  freq   unit inet_tec terrtypo        geo  time  value
0    A  PC_HH      DSL    TOTAL  EU27_2020  2021   89.5
1    A  PC_HH      DSL    TOTAL  EU27_2020  2022   86.4
2    A  PC_HH      DSL    TOTAL  EU27_2020  2023   79.7
3    A  PC_HH      DSL    TOTAL  EU27_2020  2024   74.6
4    A  PC_HH      DSL    TOTAL  EU27_2020  2025   70.3

In [ ]:
for variable in vhcn_json["id"]:

    print("\n" + "=" * 70)
    print(variable)

    labels = (
        vhcn_json["dimension"][variable]
        ["category"]
        .get("label", {})
    )

    for code, label in labels.items():
        print(code, "->", label)

======================================================================
freq
A -> Annual

======================================================================
unit
PC_HH -> Percentage of households

======================================================================
inet_tec
DSL -> Digital subscriber line (DSL)
VDSL -> Very high-speed digital subscriber line (VDSL)
VDSL2V -> Very high-speed digital subscriber line 2 vectoring (VDSL2)
DOCSIS3_0 -> Data over cable service interface specification - version 3.0 (DOCSIS 3.0)
DOCSIS3_1 -> Data over cable service interface specification - version 3.1 (DOCSIS 3.1)
FTTP -> Fibre to the premises (FTTP)
FWA -> Fixed wireless access
LTE -> Long-term evolution (LTE)
LTE_AVG -> Average long-term evolution (LTE)
5G -> Fifth generation technology standard for broadband cellular networks (5G)
5G_GHZ3P4-3P8 -> Fifth generation technology standard for broadband cellular networks (5G) in the 3.4-3.8 GHz band
SATL -> Satellite
CBL_MM -> Cable modem
WIMAX -> Worldwide interoperability for microwave access (WiMAX)
HSPA -> High speed packet access (HSPA)
BB_FX -> Fixed broadband
NGA -> Next generation access
VHCN_FX -> Fixed very high capacity networks (VHCN)
VHCN_BEREC -> Very high capacity networks (as defined by BEREC)
FTTP_DOCSIS3_0 -> Fibre to the premises and data over cable service interface specification - version 3.0
BB -> Broadband

======================================================================
terrtypo
TOTAL -> Total
DEG3 -> Rural areas

======================================================================
geo
EU27_2020 -> European Union - 27 countries (from 2020)
BE -> Belgium
BG -> Bulgaria
CZ -> Czechia
DK -> Denmark
DE -> Germany
EE -> Estonia
IE -> Ireland
EL -> Greece
ES -> Spain
FR -> France
HR -> Croatia
IT -> Italy
CY -> Cyprus
LV -> Latvia
LT -> Lithuania
LU -> Luxembourg
HU -> Hungary
MT -> Malta
NL -> Netherlands
AT -> Austria
PL -> Poland
PT -> Portugal
RO -> Romania
SI -> Slovenia
SK -> Slovakia
FI -> Finland
SE -> Sweden
IS -> Iceland
NO -> Norway
CH -> Switzerland
UK -> United Kingdom

======================================================================
time
2021 -> 2021
2022 -> 2022
2023 -> 2023
2024 -> 2024
2025 -> 2025

In [ ]:
# ============================================================
# COMPONENT 2 — CLOUD COMPUTING
# ============================================================

CLOUD_DATASET = "isoc_cicce_use"

cloud_url = (
    "https://ec.europa.eu/eurostat/api/"
    "dissemination/statistics/1.0/data/"
    f"{CLOUD_DATASET}"
    "?lang=en"
    "&sinceTimePeriod=2021"
    "&untilTimePeriod=2025"
)

response = requests.get(
    cloud_url,
    timeout=180
)

response.raise_for_status()

cloud_json = response.json()

print(
    "Cloud dimensions:",
    cloud_json["id"]
)

print(
    "Cloud sizes:",
    cloud_json["size"]
)

Cloud dimensions: ['freq', 'size_emp', 'nace_r2', 'indic_is', 'unit', 'geo', 'time']
Cloud sizes: [1, 11, 1, 31, 5, 41, 4]

In [ ]:
cloud_long = eurostat_json_to_df(
    cloud_json
)

print(
    "Cloud long shape:",
    cloud_long.shape
)

display(
    cloud_long.head()
)

Cloud long shape: (279620, 8)

  freq size_emp       nace_r2 indic_is    unit        geo  time  value
0    A      0_1  C10-S951_X_K     E_CC  PC_ENT  EU27_2020  2021    NaN
1    A      0_1  C10-S951_X_K     E_CC  PC_ENT  EU27_2020  2023    NaN
2    A      0_1  C10-S951_X_K     E_CC  PC_ENT  EU27_2020  2024    NaN
3    A      0_1  C10-S951_X_K     E_CC  PC_ENT  EU27_2020  2025    NaN
4    A      0_1  C10-S951_X_K     E_CC  PC_ENT       EU28  2021    NaN

In [ ]:
for variable in cloud_json["id"]:

    print("\n" + "=" * 70)
    print(variable)

    labels = (
        cloud_json["dimension"][variable]
        ["category"]
        .get("label", {})
    )

    for code, label in labels.items():
        print(code, "->", label)

======================================================================
freq
A -> Annual

======================================================================
size_emp
0_1 -> From 0 to 1 person employed
0-9 -> From 0 to 9 persons employed
1-4 -> From 1 to 4 persons employed
1-9 -> From 1 to 9 persons employed
2-9 -> From 2 to 9 persons employed
5-9 -> From 5 to 9 persons employed
10-49 -> From 10 to 49 persons employed
10-249 -> From 10 to 249 persons employed
GE10 -> 10 persons employed or more
50-249 -> From 50 to 249 persons employed
GE250 -> 250 persons employed or more

======================================================================
nace_r2
C10-S951_X_K -> All activities (except agriculture, forestry and fishing, and mining and quarrying), without financial sector

======================================================================
indic_is
E_CC -> Enterprises using paid cloud computing services used over the internet
E_CC_PEM -> Enterprises using e-mail (as a paid CC service)
E_CC_PSOFT -> Enterprises using office software (e.g. word processors, spreadsheets, etc.) (as a paid CC service)
E_CC_PDB -> Enterprises using hosting for the enterprise's database (as a paid CC service)
E_CC_PFIL -> Enterprises using storage of files (as a paid CC service)
E_CC_PFACC -> Enterprises using finance or accounting software applications (as a paid CC service)
E_CC_PCRM -> Enterprises using CRM software (as a paid CC service)
E_CC_PCPU -> Enterprises using computing power to run the enterprise's own software (as a paid CC service)
E_CC_PERP -> Enterprises using ERP software applications (as a paid CC service)
E_CC_PSEC -> Enterprises using security software applications (as a paid CC service)
E_CC_PDEV -> Enterprises using computing platform providing a hosted environment for application development, testing or deployment (as a paid CC service)
E_CC_PANY -> Buy at least one of the mentioned CC services - until 2020 (E_CC_PEM, E_CC_PSOFT, E_CC_PDB, E_CC_PFIL, E_CC_PFACC, E_CC_PCRM, E_CC_PCPU)
E_CC_PNONE -> Don't buy any of the mentioned CC services - until 2020 (E_CC_PEM, E_CC_PSOFT, E_CC_PDB, E_CC_PFIL, E_CC_PFACC, E_CC_PCRM, E_CC_PCPU)
E_CC1_PANY -> Enterprises using at least one of the paid CC services: CC_PEM, CC_PSOFT, CC_PFACC, CC_PERP, CC_PCRM, CC_PSEC, CC_PDB, CC_PFIL, CC_PCPU, CC_PDEV
E_CC1_PNONE -> Enterprises not using any of the paid CC services: CC_PEM, CC_PSOFT, CC_PFACC, CC_PERP, CC_PCRM, CC_PSEC, CC_PDB, CC_PFIL, CC_PCPU, CC_PDEV
E_CC_LO -> Buy only low CC services - until 2020 (e-mail, office software, storage of files)
E_CC_ME -> Buy only medium CC services - until 2020 (e-mail, office software, storage of files, hosting of the enterprise's database)
E_CC_HI -> Buy high CC services - until 2020 (accounting software applications, CRM software, computing power)
E_CC1_B -> Enterprises using only basic paid CC services, at least one of: CC_PEM, CC_PSOFT, CC_PFIL, CC_PCPU
E_CC1_I -> Enterprises using at most  intermediate paid CC services, at least one of: CC_PFACC, CC_PERP, CC_PCRMCC_PCRM
E_CC1_S -> Enterprises using sophisticated paid CC services, at least one of: CC_PSEC, CC_PDB, CC_PDEV
E_CC1_BI -> Enterprises using basic or intermediate paid CC services, at least one of:  CC_PEM, CC_PSOFT, CC_PFIL, CC_PCPU, CC_PFACC, CC_PERP, CC_PCRM
E_CC1_SI -> Enterprises using sophisticated or intermediate paid CC services, at least one of: CC_PFACC, CC_PERP, CC_PCRM, CC_PSEC, CC_PDB, CC_PDEV
E_CC1_SS_GE1 -> Enterprises using at least one of the paid CC software services: CC_PEM, CC_PSOFT, CC_PFACC, CC_PERP, CC_PCRM, CC_PSEC
E_CC1_IS_GE1 -> Enterprises using at least one of the paid CC infrastructure service: CC_PDB, CC_PFIL, CC_PCPU
E_CC1_PS -> Enterprises using paid CC platform services: CC_PDEV
E_CC_IOT -> Enterprises buying CC services and using IoT (until 2021)
E_CC_IOTX -> Enterprises buying CC services but not using IoT (until 2021)
E_CC_DA -> Enterprises using paid cloud computing services and perform data analytics
E_CC_PDBFIL -> Enterprises using hosting for the enterprise's database(s) or storage of files (as a paid CC service)
E_CC_PHW -> Enterprises using hosting for the enterprise's database(s) or storage of files or computing power (as a paid CC service)

======================================================================
unit
PC_ENT -> Percentage of enterprises
PC_ENT_CC -> Percentage of enterprises using paid CC services
PC_ENT_CUSE -> Percentage of the enterprises which use a computer
PC_ENT_IUSE -> Percentage of enterprises where persons employed have access to the internet
PC_ENT_IACC -> Percentage of the enterprises with internet access

======================================================================
geo
EU27_2020 -> European Union - 27 countries (from 2020)
EU28 -> European Union - 28 countries (2013-2020)
EU27_2007 -> European Union - 27 countries (2007-2013)
EU15 -> European Union - 15 countries (1995-2004)
EA -> Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023, EA21-2026)
BE -> Belgium
BG -> Bulgaria
CZ -> Czechia
DK -> Denmark
DE -> Germany
EE -> Estonia
IE -> Ireland
EL -> Greece
ES -> Spain
FR -> France
HR -> Croatia
IT -> Italy
CY -> Cyprus
LV -> Latvia
LT -> Lithuania
LU -> Luxembourg
HU -> Hungary
MT -> Malta
NL -> Netherlands
AT -> Austria
PL -> Poland
PT -> Portugal
RO -> Romania
SI -> Slovenia
SK -> Slovakia
FI -> Finland
SE -> Sweden
IS -> Iceland
NO -> Norway
UK -> United Kingdom
BA -> Bosnia and Herzegovina
ME -> Montenegro
MK -> North Macedonia
AL -> Albania
RS -> Serbia
TR -> Türkiye

======================================================================
time
2021 -> 2021
2023 -> 2023
2024 -> 2024
2025 -> 2025

In [ ]:
# ============================================================
# COMPONENT 3 — GDP PER CAPITA
# ============================================================

GDP_DATASET = "nama_10_pc"

gdp_url = (
    "https://ec.europa.eu/eurostat/api/"
    "dissemination/statistics/1.0/data/"
    f"{GDP_DATASET}"
    "?lang=en"
    "&sinceTimePeriod=2021"
    "&untilTimePeriod=2025"
)

response = requests.get(
    gdp_url,
    timeout=180
)

response.raise_for_status()

gdp_json = response.json()

print(
    "GDP dimensions:",
    gdp_json["id"]
)

print(
    "GDP sizes:",
    gdp_json["size"]
)

GDP dimensions: ['freq', 'unit', 'na_item', 'geo', 'time']
GDP sizes: [1, 12, 9, 46, 5]

In [ ]:
gdp_long = eurostat_json_to_df(
    gdp_json
)

print(
    "GDP long shape:",
    gdp_long.shape
)

display(
    gdp_long.head()
)

GDP long shape: (24840, 6)

  freq                      unit na_item        geo  time  value
0    A  PC_EU27_2020_HAB_MEUR_CP    B1GQ  EU27_2020  2021  100.0
1    A  PC_EU27_2020_HAB_MEUR_CP    B1GQ  EU27_2020  2022  100.0
2    A  PC_EU27_2020_HAB_MEUR_CP    B1GQ  EU27_2020  2023  100.0
3    A  PC_EU27_2020_HAB_MEUR_CP    B1GQ  EU27_2020  2024  100.0
4    A  PC_EU27_2020_HAB_MEUR_CP    B1GQ  EU27_2020  2025  100.0

In [ ]:
for variable in gdp_json["id"]:

    print("\n" + "=" * 70)
    print(variable)

    labels = (
        gdp_json["dimension"][variable]
        ["category"]
        .get("label", {})
    )

    for code, label in labels.items():
        print(code, "->", label)

======================================================================
freq
A -> Annual

======================================================================
unit
PC_EU27_2020_HAB_MEUR_CP -> Percentage of EU27 (from 2020) total per capita (based on million euro, EU27 from 2020), current prices
PC_EU27_2020_HAB_MPPS_CP -> Percentage of EU27 (from 2020) total per capita (based on million purchasing power standards, EU27 from 2020), current prices
CP_EUR_HAB -> Current prices, euro per capita
CP_NAC_HAB -> Current prices, units of national currency per capita
CP_PPS_EU27_2020_HAB -> Current prices, purchasing power standard (PPS, EU27 from 2020) per capita
CLV_I20_HAB -> Chain linked volumes, Index 2020=100, per capita
CLV_I15_HAB -> Chain linked volumes, Index 2015=100, per capita
CLV_I10_HAB -> Chain linked volumes, Index 2010=100, per capita
CLV20_EUR_HAB -> Chain linked volumes (2020), euro per capita
CLV15_EUR_HAB -> Chain linked volumes (2015), euro per capita
CLV10_EUR_HAB -> Chain linked volumes (2010), euro per capita
CLV_PCH_PRE_HAB -> Chain linked volumes, percentage change on previous period, per capita

======================================================================
na_item
B1GQ -> Gross domestic product at market prices
P3_S13 -> Final consumption expenditure of general government
P3 -> Final consumption expenditure
P31_S13 -> Individual consumption expenditure of general government
P31_S14 -> Final consumption expenditure of household
P31_S14_S15 -> Household and NPISH final consumption expenditure
P31_S15 -> Final consumption expenditure of NPISH
P32_S13 -> Collective consumption expenditure of general government
P41 -> Actual individual consumption

======================================================================
geo
EU27_2020 -> European Union - 27 countries (from 2020)
EA -> Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023, EA21-2026)
EA21 -> Euro area – 21 countries (from 2026)
EA20 -> Euro area – 20 countries (2023-2025)
EA19 -> Euro area - 19 countries  (2015-2022)
EA12 -> Euro area - 12 countries (2001-2006)
BE -> Belgium
BG -> Bulgaria
CZ -> Czechia
DK -> Denmark
DE -> Germany
EE -> Estonia
IE -> Ireland
EL -> Greece
ES -> Spain
FR -> France
HR -> Croatia
IT -> Italy
CY -> Cyprus
LV -> Latvia
LT -> Lithuania
LU -> Luxembourg
HU -> Hungary
MT -> Malta
NL -> Netherlands
AT -> Austria
PL -> Poland
PT -> Portugal
RO -> Romania
SI -> Slovenia
SK -> Slovakia
FI -> Finland
SE -> Sweden
IS -> Iceland
LI -> Liechtenstein
NO -> Norway
CH -> Switzerland
UK -> United Kingdom
BA -> Bosnia and Herzegovina
ME -> Montenegro
MD -> Moldova
MK -> North Macedonia
AL -> Albania
RS -> Serbia
TR -> Türkiye
XK -> Kosovo*

======================================================================
time
2021 -> 2021
2022 -> 2022
2023 -> 2023
2024 -> 2024
2025 -> 2025

In [ ]:
# ============================================================
# FILTER VHCN
# ============================================================

vhcn = vhcn_long[
    (vhcn_long["freq"] == "A") &
    (vhcn_long["unit"] == "PC_HH") &
    (vhcn_long["inet_tec"] == "VHCN_FX") &
    (vhcn_long["terrtypo"] == "TOTAL") &
    (vhcn_long["geo"].isin(EU27)) &
    (
        vhcn_long["time"]
        .astype(str)
        .isin(["2021", "2023", "2024", "2025"])
    )
].copy()

vhcn["year"] = vhcn["time"].astype(int)

vhcn["vhcn_pct"] = pd.to_numeric(
    vhcn["value"],
    errors="coerce"
)

vhcn = vhcn[
    ["geo", "year", "vhcn_pct"]
].sort_values(
    ["geo", "year"]
).reset_index(drop=True)

print("VHCN rows:", len(vhcn))
print("Countries:", vhcn["geo"].nunique())
print("Missing:", vhcn["vhcn_pct"].isna().sum())
print("Duplicates:", vhcn.duplicated(["geo", "year"]).sum())

display(vhcn.head(20))

VHCN rows: 108
Countries: 27
Missing: 0
Duplicates: 0

   geo  year  vhcn_pct
0   AT  2021      45.4
1   AT  2023      67.6
2   AT  2024      72.2
3   AT  2025      76.3
4   BE  2021      68.9
5   BE  2023      91.2
6   BE  2024      93.8
7   BE  2025      96.2
8   BG  2021      81.4
9   BG  2023      88.6
10  BG  2024      90.4
11  BG  2025      93.5
12  CY  2021      41.4
13  CY  2023      77.1
14  CY  2024      89.0
15  CY  2025      95.5
16  CZ  2021      52.5
17  CZ  2023      50.5
18  CZ  2024      53.9
19  CZ  2025      54.7

In [ ]:
# ============================================================
# FILTER CLOUD COMPUTING
# ============================================================

cloud = cloud_long[
    (cloud_long["freq"] == "A") &
    (cloud_long["size_emp"] == "GE10") &
    (cloud_long["nace_r2"] == "C10-S951_X_K") &
    (cloud_long["indic_is"] == "E_CC1_PANY") &
    (cloud_long["unit"] == "PC_ENT") &
    (cloud_long["geo"].isin(EU27)) &
    (
        cloud_long["time"]
        .astype(str)
        .isin(["2021", "2023", "2024", "2025"])
    )
].copy()

cloud["year"] = cloud["time"].astype(int)

cloud["cloud_pct"] = pd.to_numeric(
    cloud["value"],
    errors="coerce"
)

cloud = cloud[
    ["geo", "year", "cloud_pct"]
].sort_values(
    ["geo", "year"]
).reset_index(drop=True)

print("Cloud rows:", len(cloud))
print("Countries:", cloud["geo"].nunique())
print("Missing:", cloud["cloud_pct"].isna().sum())
print("Duplicates:", cloud.duplicated(["geo", "year"]).sum())

display(cloud.head(20))

Cloud rows: 108
Countries: 27
Missing: 23
Duplicates: 0

   geo  year  cloud_pct
0   AT  2021      39.73
1   AT  2023      46.06
2   AT  2024        NaN
3   AT  2025      51.68
4   BE  2021      52.50
5   BE  2023      51.23
6   BE  2024        NaN
7   BE  2025      61.04
8   BG  2021      12.69
9   BG  2023      17.43
10  BG  2024        NaN
11  BG  2025      17.49
12  CY  2021      50.29
13  CY  2023      52.93
14  CY  2024        NaN
15  CY  2025      51.38
16  CZ  2021      43.75
17  CZ  2023      47.15
18  CZ  2024        NaN
19  CZ  2025      54.90

In [ ]:
# ============================================================
# FILTER GDP PER CAPITA — PPS
# ============================================================

gdp = gdp_long[
    (gdp_long["freq"] == "A") &
    (gdp_long["unit"] == "CP_PPS_EU27_2020_HAB") &
    (gdp_long["na_item"] == "B1GQ") &
    (gdp_long["geo"].isin(EU27)) &
    (
        gdp_long["time"]
        .astype(str)
        .isin(["2021", "2023", "2024", "2025"])
    )
].copy()

gdp["year"] = gdp["time"].astype(int)

gdp["gdp_pc_pps"] = pd.to_numeric(
    gdp["value"],
    errors="coerce"
)

gdp = gdp[
    ["geo", "year", "gdp_pc_pps"]
].sort_values(
    ["geo", "year"]
).reset_index(drop=True)

print("GDP rows:", len(gdp))
print("Countries:", gdp["geo"].nunique())
print("Missing:", gdp["gdp_pc_pps"].isna().sum())
print("Duplicates:", gdp.duplicated(["geo", "year"]).sum())

display(gdp.head(20))

GDP rows: 108
Countries: 27
Missing: 0
Duplicates: 0

   geo  year  gdp_pc_pps
0   AT  2021     40185.6
1   AT  2023     46391.9
2   AT  2024     47527.9
3   AT  2025     49029.2
4   BE  2021     38699.2
5   BE  2023     45367.3
6   BE  2024     46587.9
7   BE  2025     47676.3
8   BG  2021     19748.1
9   BG  2023     24254.4
10  BG  2024     26324.3
11  BG  2025     28332.0
12  CY  2021     30382.9
13  CY  2023     37400.0
14  CY  2024     39456.4
15  CY  2025     40957.0
16  CZ  2021     30502.4
17  CZ  2023     34973.9
18  CZ  2024     36255.5
19  CZ  2025     38557.0

In [ ]:
# ============================================================
# LOG GDP PER CAPITA
# ============================================================

gdp["ln_gdp_pc_pps"] = np.log(
    gdp["gdp_pc_pps"]
)

display(
    gdp[
        [
            "geo",
            "year",
            "gdp_pc_pps",
            "ln_gdp_pc_pps"
        ]
    ].head()
)

  geo  year  gdp_pc_pps  ln_gdp_pc_pps
0  AT  2021     40185.6      10.601264
1  AT  2023     46391.9      10.744880
2  AT  2024     47527.9      10.769072
3  AT  2025     49029.2      10.800171
4  BE  2021     38699.2      10.563574

In [ ]:
# ============================================================
# MERGE STEP 04 ENABLERS
# ============================================================

skeleton = pd.read_csv(
    INTERMEDIATE_DIR /
    "eu27_ai_year_panel_skeleton.csv"
)

enablers = (
    skeleton
    .merge(
        vhcn,
        on=["geo", "year"],
        how="left",
        validate="one_to_one"
    )
    .merge(
        cloud,
        on=["geo", "year"],
        how="left",
        validate="one_to_one"
    )
    .merge(
        gdp,
        on=["geo", "year"],
        how="left",
        validate="one_to_one"
    )
)

print("Panel shape:", enablers.shape)

display(enablers.head(20))

Panel shape: (108, 8)

   geo   country iso3  year  vhcn_pct  cloud_pct  gdp_pc_pps  ln_gdp_pc_pps
0   AT   Austria  AUT  2021      45.4      39.73     40185.6      10.601264
1   AT   Austria  AUT  2023      67.6      46.06     46391.9      10.744880
2   AT   Austria  AUT  2024      72.2        NaN     47527.9      10.769072
3   AT   Austria  AUT  2025      76.3      51.68     49029.2      10.800171
4   BE   Belgium  BEL  2021      68.9      52.50     38699.2      10.563574
5   BE   Belgium  BEL  2023      91.2      51.23     45367.3      10.722547
6   BE   Belgium  BEL  2024      93.8        NaN     46587.9      10.749096
7   BE   Belgium  BEL  2025      96.2      61.04     47676.3      10.772190
8   BG  Bulgaria  BGR  2021      81.4      12.69     19748.1       9.890813
9   BG  Bulgaria  BGR  2023      88.6      17.43     24254.4      10.096353
10  BG  Bulgaria  BGR  2024      90.4        NaN     26324.3      10.178248
11  BG  Bulgaria  BGR  2025      93.5      17.49     28332.0      10.251747
12  CY    Cyprus  CYP  2021      41.4      50.29     30382.9      10.321635
13  CY    Cyprus  CYP  2023      77.1      52.93     37400.0      10.529426
14  CY    Cyprus  CYP  2024      89.0        NaN     39456.4      10.582952
15  CY    Cyprus  CYP  2025      95.5      51.38     40957.0      10.620278
16  CZ   Czechia  CZE  2021      52.5      43.75     30502.4      10.325561
17  CZ   Czechia  CZE  2023      50.5      47.15     34973.9      10.462357
18  CZ   Czechia  CZE  2024      53.9        NaN     36255.5      10.498346
19  CZ   Czechia  CZE  2025      54.7      54.90     38557.0      10.559893

In [ ]:
# ============================================================
# MISSINGNESS AUDIT
# ============================================================

vars_step04 = [
    "vhcn_pct",
    "cloud_pct",
    "gdp_pc_pps",
    "ln_gdp_pc_pps"
]

missing_summary = (
    enablers[vars_step04]
    .isna()
    .sum()
    .to_frame("missing_n")
)

missing_summary["missing_pct"] = (
    missing_summary["missing_n"]
    / len(enablers)
    * 100
)

display(missing_summary)

               missing_n  missing_pct
vhcn_pct               0     0.000000
cloud_pct             23    21.296296
gdp_pc_pps             0     0.000000
ln_gdp_pc_pps          0     0.000000

In [ ]:
# ============================================================
# DESCRIPTIVE STATISTICS
# ============================================================

display(
    enablers[
        [
            "vhcn_pct",
            "cloud_pct",
            "gdp_pc_pps",
            "ln_gdp_pc_pps"
        ]
    ].describe().T
)

,count,mean,std,min,25%,50%,75%,max
vhcn_pct,108.0,79.835185,15.855871,19.800000,71.775000,81.55000,93.575000,100.000000
cloud_pct,85.0,47.135176,16.693402,12.690000,35.750000,46.60000,60.380000,78.130000
gdp_pc_pps,108.0,39817.061111,16356.244024,19748.100000,29837.525000,36198.40000,43913.825000,99621.300000
ln_gdp_pc_pps,108.0,10.530364,0.331614,9.890813,10.303522,10.49677,10.689975,11.509131

In [ ]:
# ============================================================
# CORRELATION MATRIX
# ============================================================

display(
    enablers[
        [
            "vhcn_pct",
            "cloud_pct",
            "ln_gdp_pc_pps"
        ]
    ].corr()
)

               vhcn_pct  cloud_pct  ln_gdp_pc_pps
vhcn_pct       1.000000   0.205471       0.385909
cloud_pct      0.205471   1.000000       0.528060
ln_gdp_pc_pps  0.385909   0.528060       1.000000

In [ ]:
# ============================================================
# SAVE STEP 04 DATA
# ============================================================

step04_output = (
    PROCESSED_DIR /
    "Step_04_Complementary_Enablers_EU27.csv"
)

enablers.to_csv(
    step04_output,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(step04_output)

Saved:
/content/drive/MyDrive/AI_Realization_Gap_EU27/03_processed_data/Step_04_Complementary_Enablers_EU27.csv

In [ ]:
# ============================================================
# STEP 04 QUALITY CONTROL
# ============================================================

qc_checks = {
    "Panel N = 108":
        len(enablers) == 108,

    "Countries = 27":
        enablers["iso3"].nunique() == 27,

    "Years = 4":
        enablers["year"].nunique() == 4,

    "No duplicate country-year":
        enablers.duplicated(
            ["iso3", "year"]
        ).sum() == 0,

    "VHCN missing = 0":
        enablers["vhcn_pct"].isna().sum() == 0,

    "Cloud data recorded (auxiliary)":
        enablers["cloud_pct"].notna().sum() + enablers["cloud_pct"].isna().sum() == len(enablers),

    "GDP missing = 0":
        enablers["gdp_pc_pps"].isna().sum() == 0
}

qc = pd.DataFrame({
    "check": qc_checks.keys(),
    "passed": qc_checks.values()
})

display(qc)
print("Cloud missing (auxiliary):", enablers["cloud_pct"].isna().sum())

                       check  passed
0              Panel N = 108    True
1             Countries = 27    True
2                  Years = 4    True
3  No duplicate country-year    True
4           VHCN missing = 0    True
5          Cloud missing = 0   False
6            GDP missing = 0    True

In [ ]:
qc_path = (
    LOG_DIR /
    "Step_04_QC.csv"
)

qc.to_csv(
    qc_path,
    index=False,
    encoding="utf-8-sig"
)

print(qc_path)

/content/drive/MyDrive/AI_Realization_Gap_EU27/08_logs/Step_04_QC.csv

In [ ]:
# ============================================================
# CLOUD MISSINGNESS PATTERN
# ============================================================

cloud_missing = enablers[
    enablers["cloud_pct"].isna()
][
    ["geo", "country", "iso3", "year"]
].sort_values(
    ["year", "country"]
)

display(cloud_missing)

print("\nMissing cloud observations by year:")

display(
    cloud_missing
    .groupby("year")
    .size()
    .reset_index(name="missing_n")
)

    geo     country iso3  year
2    AT     Austria  AUT  2024
6    BE     Belgium  BEL  2024
10   BG    Bulgaria  BGR  2024
14   CY      Cyprus  CYP  2024
18   CZ     Czechia  CZE  2024
26   DK     Denmark  DNK  2024
34   EE     Estonia  EST  2024
38   FI     Finland  FIN  2024
42   FR      France  FRA  2024
22   DE     Germany  DEU  2024
46   EL      Greece  GRC  2024
58   IE     Ireland  IRL  2024
62   IT       Italy  ITA  2024
74   LV      Latvia  LVA  2024
66   LT   Lithuania  LTU  2024
70   LU  Luxembourg  LUX  2024
78   MT       Malta  MLT  2024
86   PL      Poland  POL  2024
90   PT    Portugal  PRT  2024
94   RO     Romania  ROU  2024
98   SK    Slovakia  SVK  2024
102  SI    Slovenia  SVN  2024
106  SE      Sweden  SWE  2024

Missing cloud observations by year:

   year  missing_n
0  2024         23

In [ ]:
# ============================================================
# STEP 04 — MAIN BALANCED ENABLERS DATASET
# ============================================================

step04_main = enablers[
    [
        "geo",
        "country",
        "iso3",
        "year",
        "vhcn_pct",
        "gdp_pc_pps",
        "ln_gdp_pc_pps"
    ]
].copy()

print("Panel N:", len(step04_main))
print("Countries:", step04_main["iso3"].nunique())
print("Years:", sorted(step04_main["year"].unique()))

print("\nMissing values:")
display(
    step04_main
    .isna()
    .sum()
    .to_frame("missing_n")
)

Panel N: 108
Countries: 27
Years: [np.int64(2021), np.int64(2023), np.int64(2024), np.int64(2025)]

Missing values:

               missing_n
geo                    0
country                0
iso3                   0
year                   0
vhcn_pct               0
gdp_pc_pps             0
ln_gdp_pc_pps          0

In [ ]:
# ============================================================
# CLOUD — ROBUSTNESS / AUXILIARY VARIABLE
# ============================================================

cloud_aux = enablers[
    [
        "geo",
        "country",
        "iso3",
        "year",
        "cloud_pct"
    ]
].copy()

print(
    "Observed cloud:",
    cloud_aux["cloud_pct"].notna().sum()
)

print(
    "Missing cloud:",
    cloud_aux["cloud_pct"].isna().sum()
)

Observed cloud: 85
Missing cloud: 23

In [ ]:
# ============================================================
# SAVE STEP 04
# ============================================================

main_output = (
    PROCESSED_DIR /
    "Step_04_Complementary_Enablers_EU27.csv"
)

cloud_output = (
    INTERMEDIATE_DIR /
    "Step_04_Cloud_auxiliary_EU27.csv"
)

step04_main.to_csv(
    main_output,
    index=False,
    encoding="utf-8-sig"
)

cloud_aux.to_csv(
    cloud_output,
    index=False,
    encoding="utf-8-sig"
)

print(main_output)
print(cloud_output)

/content/drive/MyDrive/AI_Realization_Gap_EU27/03_processed_data/Step_04_Complementary_Enablers_EU27.csv
/content/drive/MyDrive/AI_Realization_Gap_EU27/02_intermediate_data/Step_04_Cloud_auxiliary_EU27.csv

In [ ]:
# ============================================================
# STEP 04 FINAL QC
# ============================================================

qc_checks = {

    "Panel N = 108":
        len(step04_main) == 108,

    "Countries = 27":
        step04_main["iso3"].nunique() == 27,

    "Years = 4":
        step04_main["year"].nunique() == 4,

    "Correct years":
        set(step04_main["year"]) ==
        {2021, 2023, 2024, 2025},

    "No duplicate country-year":
        step04_main.duplicated(
            ["iso3", "year"]
        ).sum() == 0,

    "VHCN missing = 0":
        step04_main["vhcn_pct"].isna().sum() == 0,

    "GDP missing = 0":
        step04_main["gdp_pc_pps"].isna().sum() == 0,

    "Log GDP missing = 0":
        step04_main["ln_gdp_pc_pps"].isna().sum() == 0
}

qc = pd.DataFrame({
    "check": qc_checks.keys(),
    "passed": qc_checks.values()
})

display(qc)

qc.to_csv(
    LOG_DIR / "Step_04_QC.csv",
    index=False,
    encoding="utf-8-sig"
)

                       check  passed
0              Panel N = 108    True
1             Countries = 27    True
2                  Years = 4    True
3              Correct years    True
4  No duplicate country-year    True
5           VHCN missing = 0    True
6            GDP missing = 0    True
7        Log GDP missing = 0    True

In [ ]:
# ============================================================
# DOWNLOAD STEP 04 OUTPUTS AS ZIP
# ============================================================

from pathlib import Path
import zipfile
try:
    from google.colab import files
except ImportError:
    files = None

step04_files = [
    PROJECT_ROOT / "03_processed_data" / "Step_04_Complementary_Enablers_EU27.csv",
    PROJECT_ROOT / "02_intermediate_data" / "Step_04_Cloud_auxiliary_EU27.csv",
    PROJECT_ROOT / "08_logs" / "Step_04_QC.csv"
]

zip_path = Path("/content/Step_04_outputs.zip")

print("Files to include:\n")

for f in step04_files:
    print(f.name, "->", f.exists())

with zipfile.ZipFile(
    zip_path,
    "w",
    zipfile.ZIP_DEFLATED
) as z:

    for f in step04_files:
        if not f.exists():
            raise FileNotFoundError(f"Missing required Step 04 output: {f}")
        z.write(f, arcname=f.name)

print("\nZIP created:")
print(zip_path)

if files is not None:
    files.download(str(zip_path))
else:
    print("Download manually:", zip_path)

Files to include:

Step_04_Complementary_Enablers_EU27.csv -> True
Step_04_Cloud_auxiliary_EU27.csv -> True
Step_04_QC.csv -> True

ZIP created:
/content/Step_04_outputs.zip